
export const countries = [
    { id: 1, code: 'AED', country: 'United Arab Emirates Dirham' },
    { id: 2, code: 'ARS', country: 'Argentine Peso' },
    { id: 3, code: 'AUD', country: 'Australian Dollar' },
    { id: 4, code: 'AZN', country: 'Azerbaijani Manat' },
    { id: 5, code: 'BGN', country: 'Bulgarian Lev' },
    { id: 6, code: 'BHD', country: 'Bahraini Dinar' },
    { id: 7, code: 'BHD', country: 'Bahraini Dinar' },
    { id: 8, code: 'BND', country: 'Brunei Dollar' },
    { id: 9, code: 'BRL', country: 'Brazilian Real' },
    { id: 10, code: 'CAD', country: 'Canadian Dollar' },
    { id: 11, code: 'CHF', country: 'Swiss Franc' },
    { id: 12, code: 'CLP', country: 'Chilean Peso' },
    { id: 13, code: 'CNY', country: 'Chinese Yuan' },
    { id: 14, code: 'CZK', country: 'Czech Koruna' },
    { id: 15, code: 'DKK', country: 'Danish Krone' },
    { id: 16, code: 'EGP', country: 'Egyptian Pound' },
    { id: 17, code: 'EUR', country: 'Euro' },
    { id: 18, code: 'FJD', country: 'Fiji Dollar' },
    { id: 19, code: 'GBP', country: 'Pound Sterling' },
    { id: 20, code: 'HKD', country: 'Hong Kong Dollar' },
    { id: 21, code: 'HUF', country: 'Hungarian Forint' },
    { id: 22, code: 'IDR', country: 'Indonesian rRpiah' },
    { id: 23, code: 'ILS', country: 'Israeli New Shekel' },
    { id: 24, code: 'INR', country: 'Indian Rupee' },
    { id: 25, code: 'JPY', country: 'Japanese Yen' },
    { id: 26, code: 'KRW', country: 'South Korean Won' },
    { id: 27, code: 'KWD', country: 'Kuwaiti Dinar' },
    { id: 28, code: 'LKR', country: 'Sri Lankan Rupee' },
    { id: 29, code: 'MAD', country: 'Moroccan Dirham' },
    { id: 30, code: 'MGA', country: 'Malagasy Ariary' },
    { id: 31, code: 'MXN', country: 'Mexican Peso' },
    { id: 32, code: 'MYR', country: 'Malaysian Ringgit' },
    { id: 33, code: 'NOK', country: 'Norwegian Krone' },
    { id: 34, code: 'NZD', country: 'New Zealand Dollar' },
    { id: 35, code: 'OMR', country: 'Omani Rial' },
    { id: 36, code: 'PEN', country: 'Peruvian Sol' },
    { id: 37, code: 'PGK', country: 'Papua New Guinean Kina' },
    { id: 38, code: 'PHP', country: 'Philippine Peso' },
    { id: 39, code: 'PKR', country: 'Pakistani Rupee' },
    { id: 40, code: 'PLN', country: 'Polish Złoty' },
    { id: 41, code: 'RUB', country: 'Russian Ruble' },
    { id: 42, code: 'SAR', country: 'Saudi Riyal' },
    { id: 43, code: 'SBD', country: 'Solomon Islands Dollar' },
    { id: 44, code: 'SCR', country: 'Seychelles Rupee' },
    { id: 45, code: 'SEK', country: 'Swedish Krona/Kronor' },
    { id: 46, code: 'SGD', country: 'Singapore Dollar' },
    { id: 47, code: 'THB', country: 'Thai Baht' },
    { id: 48, code: 'TOP', country: 'Tongan pPaʻanga' },
    { id: 49, code: 'TRY', country: 'Turkish Lira' },
    { id: 50, code: 'TWD', country: 'New Taiwan Dollar' },
    { id: 51, code: 'TZS', country: 'Tanzanian Shilling' },
    { id: 52, code: 'USD', country: 'United States Dollar' },
    { id: 53, code: 'VEF', country: 'Venezuelan Bolívar' },
    { id: 54, code: 'VND', country: 'Vietnamese Dồng' },
    { id: 55, code: 'VUV', country: 'Vanuatu Vatu' },
    { id: 56, code: 'WST', country: 'Samoan Tala' },
    { id: 57, code: 'CFA', country: 'CFA Franc' },
    { id: 58, code: 'ZAR', country: 'South African Rand' },
]